In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn as skl
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from sklearn import model_selection, datasets, linear_model, metrics
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

from sklearn.linear_model import LinearRegression #Линейная регрессия
from sklearn.ensemble import RandomForestRegressor #Случайный лес
from sklearn.linear_model import Ridge #Ридж регрессия
from sklearn.linear_model import Lasso #Лассо регрессия
from sklearn.svm import SVR #метод опорных векторов
from sklearn.linear_model import BayesianRidge #байесовская регрессия
from sklearn.neighbors import KNeighborsRegressor as KNNr #K-ближайших соседей
from sklearn.ensemble import GradientBoostingRegressor #Градиентный бустинг

from scipy.optimize import linprog

# Первичный взгляд на данные

In [4]:
train = pd.read_csv('train.csv')
train.head()

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),y
0,990025,Large Magellanic Cloud (LMC),0.628657,63.125200,27109.234310,0.646039,8.240543,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.052590
1,990025,Camelopardalis B,0.818082,81.004994,30166.793958,0.852246,10.671823,4.742470,0.833624,0.467873,...,NaN,NaN,NaN,NaN,NaN,19.177926,NaN,22.785018,NaN,0.059868
2,990025,Virgo I,0.659443,59.570534,8441.707353,0.499762,8.840316,5.583973,0.469110,0.363837,...,NaN,NaN,NaN,NaN,NaN,21.151265,6.534020,NaN,NaN,0.050449
3,990025,UGC 8651 (DDO 181),0.555862,52.333293,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.912194,NaN,NaN,0.049394
4,990025,Tucana Dwarf,0.991196,81.802464,81033.956906,1.131163,13.800672,13.188907,0.910341,0.918353,...,NaN,NaN,NaN,NaN,NaN,NaN,5.611753,NaN,NaN,0.154247

In [5]:
test = pd.read_csv('test.csv')
test.head()

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII)
0,1007012,KK98 77,0.456086,51.562543,12236.576447,0.593325,10.414164,10.699072,0.547114,0.556267,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1007012,Reticulum III,0.529835,57.228262,3431.883825,0.675407,7.239485,5.311122,0.497688,0.409969,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1008016,Reticulum III,0.560976,59.379539,27562.914252,0.594624,11.774890,5.937797,0.544744,0.486167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1007012,Segue 1,0.565910,59.952390,20352.232905,0.837700,11.613621,10.067882,0.691641,0.523441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1013042,Virgo I,0.588274,55.428320,23959.704016,0.520579,10.392416,6.374637,0.530676,0.580418,...,7.357729,0.583373,0.600445,0.856158,206.674424,224.104054,NaN,7.687626,NaN,NaN

In [6]:
print('количество строк и столбцов в train: ' + str(train.shape) + '; всего значений: ' + str(train.shape[0]*train.shape[1]))
print('количество строк и столбцов в test: ' + str(test.shape) + '; всего значений: ' + str(test.shape[0]*test.shape[1]))

количество строк и столбцов в train: (3865, 80); всего значений: 309200
количество строк и столбцов в test: (890, 79); всего значений: 70310

In [7]:
print('Всего в train '+str(len(train.galaxy.unique()))+' галактика (страна); ' + str(len(train['galactic year'].unique())) + ' галактических лет')
print('Всего в test '+str(len(test.galaxy.unique()))+' галактика (страна); ' + str(len(test['galactic year'].unique())) + ' галактических лет')

Всего в train 181 галактика (страна); 26 галактических лет
Всего в test 172 галактика (страна); 10 галактических лет

In [8]:
a = set(train['galactic year'].unique())
b = set(test['galactic year'].unique())

print('Галактика, не входящая в train, но входящая в test')
print(b.difference(a))

Галактика, не входящая в train, но входящая в test
{1016064}

In [9]:
test_c = set(test.columns)
train_c = set(train.columns)

print('В тест не входит столбец ')
print(train_c.difference(test_c))

В тест не входит столбец
{'y'}

In [10]:
#удаление ненужных галактик из train
filt = list(test.galaxy.unique())
train = train.query('galaxy == @filt')

len(train['galaxy'].unique())

172

# Заполнение пропусков

In [11]:
train["galaxy"] = train["galaxy"].astype('category')
train["galaxy"] = train["galaxy"].cat.codes


test["galaxy"] = test["galaxy"].astype('category')
test["galaxy"] = test["galaxy"].cat.codes

In [12]:
imp = IterativeImputer(max_iter=10, random_state=0)

imp.fit(train.values)
tr_new = imp.transform(train.values)

imp.fit(train.iloc[:,:-1].values)
tr_new1 = imp.transform(test.values)

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\sklearn\impute\_iterative.py:670: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  " reached.", ConvergenceWarning)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\sklearn\impute\_iterative.py:670: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  " reached.", ConvergenceWarning)

In [13]:
tr_n = pd.DataFrame(tr_new)
tr_n1 = pd.DataFrame(tr_new1)

tr_n.columns = train.columns
tr_n1.columns = test.columns
tr_n1.head()

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII)
0,1007012.0,78.0,0.456086,51.562543,12236.576447,0.593325,10.414164,10.699072,0.547114,0.556267,...,8.176749,0.602555,0.637036,0.969703,180.082187,189.685435,10.429761,11.493536,21.706622,0.880640
1,1007012.0,135.0,0.529835,57.228262,3431.883825,0.675407,7.239485,5.311122,0.497688,0.409969,...,7.608054,0.454300,0.533988,0.864666,207.186534,207.892979,8.571801,8.691854,20.785533,0.939801
2,1008016.0,135.0,0.560976,59.379539,27562.914252,0.594624,11.774890,5.937797,0.544744,0.486167,...,7.421059,0.516924,0.581656,0.889696,195.683820,197.982401,12.694055,9.725756,23.424221,0.921074
3,1007012.0,140.0,0.565910,59.952390,20352.232905,0.837700,11.613621,10.067882,0.691641,0.523441,...,8.023184,0.588343,0.636598,0.925058,175.761753,179.126604,14.080313,9.157850,22.814842,0.829622
4,1013042.0,169.0,0.588274,55.428320,23959.704016,0.520579,10.392416,6.374637,0.530676,0.580418,...,7.357729,0.583373,0.600445,0.856158,206.674424,224.104054,5.828995,7.687626,22.220501,0.937344

In [14]:
tr_n1.to_csv('test_full.csv')

# Взгляд на данные

In [15]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3664 entries, 0 to 3864
Data columns (total 80 columns):
galactic year                                                                              3664 non-null int64
galaxy                                                                                     3664 non-null int16
existence expectancy index                                                                 3664 non-null float64
existence expectancy at birth                                                              3664 non-null float64
Gross income per capita                                                                    3636 non-null float64
Income Index                                                                               3636 non-null float64
Expected years of education (galactic years)                                               3547 non-null float64
Mean years of education (galactic years)                                                   3312 non-null float64
Intergalactic Development Index (IDI)                                                      3289 non-null float64
Education Index                                                                            3289 non-null float64
Intergalactic Development Index (IDI), Rank                                                3247 non-null float64
Population using at least basic drinking-water services (%)                                1901 non-null float64
Population using at least basic sanitation services (%)                                    1895 non-null float64
Gross capital formation (% of GGP)                                                         1428 non-null float64
Population, total (millions)                                                               1198 non-null float64
Population, urban (%)                                                                      1198 non-null float64
Mortality rate, under-five (per 1,000 live births)                                         1198 non-null float64
Mortality rate, infant (per 1,000 live births)                                             1186 non-null float64
Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64))           1192 non-null float64
Population, ages 15–64 (millions)                                                          1192 non-null float64
Population, ages 65 and older (millions)                                                   1192 non-null float64
Life expectancy at birth, male (galactic years)                                            1192 non-null float64
Life expectancy at birth, female (galactic years)                                          1192 non-null float64
Population, under age 5 (millions)                                                         1192 non-null float64
Young age (0-14) dependency ratio (per 100 creatures ages 15-64)                           1192 non-null float64
Adolescent birth rate (births per 1,000 female creatures ages 15-19)                       1180 non-null float64
Total unemployment rate (female to male ratio)                                             1171 non-null float64
Vulnerable employment (% of total employment)                                              1171 non-null float64
Unemployment, total (% of labour force)                                                    1171 non-null float64
Employment in agriculture (% of total employment)                                          1171 non-null float64
Labour force participation rate (% ages 15 and older)                                      1171 non-null float64
Labour force participation rate (% ages 15 and older), female                              1171 non-null float64
Employment in services (% of total employment)                                             1171 non-null float64
Labour force participation rate (% ages 15 and older), male                                1171 non-null float64
Employment to population ratio (% ages 15 and older)                                       1171 non-null float64
Jungle area (% of total land area)                                                         1164 non-null float64
Share of employment in nonagriculture, female (% of total employment in nonagriculture)    1171 non-null float64
Youth unemployment rate (female to male ratio)                                             1170 non-null float64
Unemployment, youth (% ages 15–24)                                                         1170 non-null float64
Mortality rate, female grown up (per 1,000 people)                                         1182 non-null float64
Mortality rate, male grown up (per 1,000 people)                                           1182 non-null float64
Infants lacking immunization, red hot disease (% of one-galactic year-olds)                1146 non-null float64
Infants lacking immunization, Combination Vaccine (% of one-galactic year-olds)            1146 non-null float64
Gross galactic product (GGP) per capita                                                    1139 non-null float64
Gross galactic product (GGP), total                                                        1139 non-null float64
Outer Galaxies direct investment, net inflows (% of GGP)                                   1111 non-null float64
Exports and imports (% of GGP)                                                             1078 non-null float64
Share of seats in senate (% held by female)                                                1055 non-null float64
Natural resource depletion                                                                 1079 non-null float64
Mean years of education, female (galactic years)                                           1074 non-null float64
Mean years of education, male (galactic years)                                             1072 non-null float64
Expected years of education, female (galactic years)                                       1048 non-null float64
Expected years of education, male (galactic years)                                         1047 non-null float64
Maternal mortality ratio (deaths per 100,000 live births)                                  1180 non-null float64
Renewable energy consumption (% of total final energy consumption)                         1163 non-null float64
Estimated gross galactic income per capita, male                                           996 non-null float64
Estimated gross galactic income per capita, female                                         996 non-null float64
Rural population with access to electricity (%)                                            968 non-null float64
Domestic credit provided by financial sector (% of GGP)                                    1021 non-null float64
Population with at least some secondary education, female (% ages 25 and older)            1023 non-null float64
Population with at least some secondary education, male (% ages 25 and older)              1021 non-null float64
Gross fixed capital formation (% of GGP)                                                   1023 non-null float64
Remittances, inflows (% of GGP)                                                            977 non-null float64
Population with at least some secondary education (% ages 25 and older)                    988 non-null float64
Intergalactic inbound tourists (thousands)                                                 939 non-null float64
Gross enrolment ratio, primary (% of primary under-age population)                         986 non-null float64
Respiratory disease incidence (per 100,000 people)                                         840 non-null float64
Interstellar phone subscriptions (per 100 people)                                          839 non-null float64
Interstellar Data Net users, total (% of population)                                       821 non-null float64
Current health expenditure (% of GGP)                                                      814 non-null float64
Intergalactic Development Index (IDI), female                                              859 non-null float64
Intergalactic Development Index (IDI), male                                                858 non-null float64
Gender Development Index (GDI)                                                             857 non-null float64
Intergalactic Development Index (IDI), female, Rank                                        836 non-null float64
Intergalactic Development Index (IDI), male, Rank                                          835 non-null float64
Adjusted net savings                                                                       883 non-null float64
Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total                  914 non-null float64
Private galaxy capital flows (% of GGP)                                                    825 non-null float64
Gender Inequality Index (GII)                                                              788 non-null float64
y                                                                                          3664 non-null float64
dtypes: float64(78), int16(1), int64(1)
memory usage: 2.2 MB

In [16]:
train.head()

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),y
0,990025,90,0.628657,63.125200,27109.234310,0.646039,8.240543,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.052590
1,990025,28,0.818082,81.004994,30166.793958,0.852246,10.671823,4.742470,0.833624,0.467873,...,NaN,NaN,NaN,NaN,NaN,19.177926,NaN,22.785018,NaN,0.059868
2,990025,169,0.659443,59.570534,8441.707353,0.499762,8.840316,5.583973,0.469110,0.363837,...,NaN,NaN,NaN,NaN,NaN,21.151265,6.534020,NaN,NaN,0.050449
3,990025,154,0.555862,52.333293,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.912194,NaN,NaN,0.049394
5,990025,84,0.824692,63.887135,28409.062695,0.671697,14.062458,9.978597,0.815264,0.796807,...,NaN,NaN,NaN,NaN,NaN,40.118699,3.981105,21.012897,NaN,0.052871

In [17]:
test.info() # количество ненулевых строк в столбце и тип строки

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 890 entries, 0 to 889
Data columns (total 79 columns):
galactic year                                                                              890 non-null int64
galaxy                                                                                     890 non-null int16
existence expectancy index                                                                 885 non-null float64
existence expectancy at birth                                                              885 non-null float64
Gross income per capita                                                                    885 non-null float64
Income Index                                                                               885 non-null float64
Expected years of education (galactic years)                                               885 non-null float64
Mean years of education (galactic years)                                                   882 non-null float64
Intergalactic Development Index (IDI)                                                      882 non-null float64
Education Index                                                                            882 non-null float64
Intergalactic Development Index (IDI), Rank                                                880 non-null float64
Population using at least basic drinking-water services (%)                                880 non-null float64
Population using at least basic sanitation services (%)                                    880 non-null float64
Gross capital formation (% of GGP)                                                         828 non-null float64
Population, total (millions)                                                               615 non-null float64
Population, urban (%)                                                                      615 non-null float64
Mortality rate, under-five (per 1,000 live births)                                         615 non-null float64
Mortality rate, infant (per 1,000 live births)                                             615 non-null float64
Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64))           610 non-null float64
Population, ages 15–64 (millions)                                                          610 non-null float64
Population, ages 65 and older (millions)                                                   610 non-null float64
Life expectancy at birth, male (galactic years)                                            610 non-null float64
Life expectancy at birth, female (galactic years)                                          610 non-null float64
Population, under age 5 (millions)                                                         610 non-null float64
Young age (0-14) dependency ratio (per 100 creatures ages 15-64)                           610 non-null float64
Adolescent birth rate (births per 1,000 female creatures ages 15-19)                       610 non-null float64
Total unemployment rate (female to male ratio)                                             605 non-null float64
Vulnerable employment (% of total employment)                                              605 non-null float64
Unemployment, total (% of labour force)                                                    605 non-null float64
Employment in agriculture (% of total employment)                                          605 non-null float64
Labour force participation rate (% ages 15 and older)                                      605 non-null float64
Labour force participation rate (% ages 15 and older), female                              605 non-null float64
Employment in services (% of total employment)                                             605 non-null float64
Labour force participation rate (% ages 15 and older), male                                605 non-null float64
Employment to population ratio (% ages 15 and older)                                       605 non-null float64
Jungle area (% of total land area)                                                         608 non-null float64
Share of employment in nonagriculture, female (% of total employment in nonagriculture)    605 non-null float64
Youth unemployment rate (female to male ratio)                                             605 non-null float64
Unemployment, youth (% ages 15–24)                                                         605 non-null float64
Mortality rate, female grown up (per 1,000 people)                                         595 non-null float64
Mortality rate, male grown up (per 1,000 people)                                           595 non-null float64
Infants lacking immunization, red hot disease (% of one-galactic year-olds)                615 non-null float64
Infants lacking immunization, Combination Vaccine (% of one-galactic year-olds)            615 non-null float64
Gross galactic product (GGP) per capita                                                    605 non-null float64
Gross galactic product (GGP), total                                                        605 non-null float64
Outer Galaxies direct investment, net inflows (% of GGP)                                   610 non-null float64
Exports and imports (% of GGP)                                                             589 non-null float64
Share of seats in senate (% held by female)                                                600 non-null float64
Natural resource depletion                                                                 591 non-null float64
Mean years of education, female (galactic years)                                           575 non-null float64
Mean years of education, male (galactic years)                                             575 non-null float64
Expected years of education, female (galactic years)                                       595 non-null float64
Expected years of education, male (galactic years)                                         595 non-null float64
Maternal mortality ratio (deaths per 100,000 live births)                                  530 non-null float64
Renewable energy consumption (% of total final energy consumption)                         534 non-null float64
Estimated gross galactic income per capita, male                                           605 non-null float64
Estimated gross galactic income per capita, female                                         605 non-null float64
Rural population with access to electricity (%)                                            615 non-null float64
Domestic credit provided by financial sector (% of GGP)                                    569 non-null float64
Population with at least some secondary education, female (% ages 25 and older)            550 non-null float64
Population with at least some secondary education, male (% ages 25 and older)              550 non-null float64
Gross fixed capital formation (% of GGP)                                                   556 non-null float64
Remittances, inflows (% of GGP)                                                            576 non-null float64
Population with at least some secondary education (% ages 25 and older)                    540 non-null float64
Intergalactic inbound tourists (thousands)                                                 574 non-null float64
Gross enrolment ratio, primary (% of primary under-age population)                         504 non-null float64
Respiratory disease incidence (per 100,000 people)                                         615 non-null float64
Interstellar phone subscriptions (per 100 people)                                          613 non-null float64
Interstellar Data Net users, total (% of population)                                       603 non-null float64
Current health expenditure (% of GGP)                                                      606 non-null float64
Intergalactic Development Index (IDI), female                                              560 non-null float64
Intergalactic Development Index (IDI), male                                                560 non-null float64
Gender Development Index (GDI)                                                             560 non-null float64
Intergalactic Development Index (IDI), female, Rank                                        549 non-null float64
Intergalactic Development Index (IDI), male, Rank                                          549 non-null float64
Adjusted net savings                                                                       519 non-null float64
Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total                  482 non-null float64
Private galaxy capital flows (% of GGP)                                                    536 non-null float64
Gender Inequality Index (GII)                                                              529 non-null float64
dtypes: float64(77), int16(1), int64(1)
memory usage: 544.2 KB

In [18]:
desc = train.describe().T # основные сттистические показатели 
desc

,count,mean,std,min,25%,50%,75%,max
galactic year,3664.0,1.000638e+06,6917.134609,990025.000000,995006.000000,1000000.000000,1.005006e+06,1.015056e+06
galaxy,3664.0,8.615857e+01,49.591509,0.000000,43.000000,86.000000,1.290000e+02,1.710000e+02
existence expectancy index,3664.0,8.697104e-01,0.162028,0.227890,0.759411,0.904492,9.899363e-01,1.246908e+00
existence expectancy at birth,3664.0,7.661038e+01,10.462702,34.244062,69.524887,78.789404,8.439609e+01,1.002101e+02
Gross income per capita,3636.0,3.135404e+04,18462.818417,-126.906522,20013.636620,26423.983119,3.673058e+04,1.510727e+05
Income Index,3636.0,8.221158e-01,0.192918,0.292001,0.674836,0.824272,9.666525e-01,1.326911e+00
Expected years of education (galactic years),3547.0,1.465829e+01,3.653047,3.799663,12.472253,14.881222,1.709354e+01,2.695594e+01
Mean years of education (galactic years),3312.0,1.028593e+01,3.338815,1.928166,7.650666,10.405407,1.289633e+01,1.905765e+01
Intergalactic Development Index (IDI),3289.0,8.020458e-01,0.176713,0.273684,0.669714,0.821732,9.383288e-01,1.232814e+00
Education Index,3289.0,7.440325e-01,0.201851,0.189874,0.591228,0.759541,8.931124e-01,1.269625e+00
"Intergalactic Development Index (IDI), Rank",3247.0,1.356457e+02,52.586004,9.925906,92.582685,137.268145,1.759774e+02,2.787866e+02
Population using at least basic drinking-water services (%),1901.0,1.013796e+02,20.507354,33.135967,88.810980,108.034225,1.165857e+02,1.363218e+02
Population using at least basic sanitation services (%),1895.0,9.921871e+01,32.410243,10.609505,72.209039,109.334597,1.250658e+02,1.584142e+02
Gross capital formation (% of GGP),1428.0,3.207147e+01,8.502315,2.486353,27.273854,31.338616,3.625096e+01,7.230582e+01
"Population, total (millions)",1198.0,8.959777e+02,918.368912,-160.436179,599.557785,772.762074,9.488835e+02,7.993324e+03
"Population, urban (%)",1198.0,7.710591e+01,23.749055,20.784384,57.772120,77.438084,9.668349e+01,1.299121e+02
"Mortality rate, under-five (per 1,000 live births)",1198.0,9.858004e+01,56.052103,9.723443,58.885375,80.184121,1.255837e+02,3.794197e+02
"Mortality rate, infant (per 1,000 live births)",1186.0,6.568580e+01,34.148340,12.790939,39.756564,56.054048,8.476969e+01,2.085021e+02
Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64)),1192.0,1.885614e+01,7.572278,4.297445,13.466201,16.635906,2.320374e+01,5.221623e+01
"Population, ages 15–64 (millions)",1192.0,5.837751e+02,586.411353,-91.294595,394.201866,501.743291,6.154198e+02,5.542809e+03
"Population, ages 65 and older (millions)",1192.0,6.562470e+01,64.845572,-23.658715,43.497424,56.898895,6.975997e+01,6.494931e+02
"Life expectancy at birth, male (galactic years)",1192.0,7.447176e+01,9.902837,39.156694,67.720479,76.358476,8.172546e+01,9.554193e+01
"Life expectancy at birth, female (galactic years)",1192.0,7.994585e+01,10.686916,40.938180,72.524989,82.381130,8.793092e+01,1.016758e+02
"Population, under age 5 (millions)",1192.0,9.050139e+01,92.079801,-2.089459,60.423291,77.691358,9.541273e+01,7.809644e+02
Young age (0-14) dependency ratio (per 100 creatures ages 15-64),1192.0,7.868754e+01,25.359134,11.622025,56.908804,76.296661,1.000303e+02,1.355494e+02
"Adolescent birth rate (births per 1,000 female creatures ages 15-19)",1180.0,1.146506e+02,51.848729,14.344434,74.463841,106.449747,1.460631e+02,2.898083e+02
Total unemployment rate (female to male ratio),1171.0,2.771458e+00,1.365128,0.926083,2.189471,2.574963,3.055123e+00,2.965666e+01
Vulnerable employment (% of total employment),1171.0,6.981661e+01,29.790390,11.659018,45.035924,66.160785,9.425210e+01,1.439322e+02
"Unemployment, total (% of labour force)",1171.0,1.466313e+01,6.796829,1.957005,9.807565,13.347330,1.794851e+01,4.485249e+01
Employment in agriculture (% of total employment),1171.0,5.463345e+01,24.968652,-0.682781,34.788175,50.717870,7.216230e+01,1.310921e+02
...,...,...,...,...,...,...,...,...
"Mean years of education, male (galactic years)",1072.0,1.087239e+01,3.136641,2.948515,8.504201,10.864631,1.325255e+01,1.913696e+01
"Expected years of education, female (galactic years)",1048.0,1.562142e+01,4.049085,3.732250,13.137041,15.936491,1.845916e+01,2.698159e+01
"Expected years of education, male (galactic years)",1047.0,1.494325e+01,3.276452,3.840845,13.083751,14.919635,1.702335e+01,2.904519e+01
"Maternal mortality ratio (deaths per 100,000 live births)",1180.0,5.599269e+02,363.280900,39.176506,323.308419,446.867081,6.894127e+02,3.178334e+03
Renewable energy consumption (% of total final energy consumption),1163.0,6.449024e+01,32.307787,-1.047957,38.829498,56.829982,8.861104e+01,1.461307e+02
"Estimated gross galactic income per capita, male",996.0,4.151392e+04,23590.809023,4247.338987,26617.359628,34802.678609,4.890477e+04,1.876636e+05
"Estimated gross galactic income per capita, female",996.0,2.281515e+04,12762.088154,-947.544715,14615.655532,19234.213503,2.717313e+04,8.363878e+04
Rural population with access to electricity (%),968.0,1.078065e+02,39.748904,1.527037,75.731564,123.489926,1.382708e+02,1.749134e+02
Domestic credit provided by financial sector (% of GGP),1021.0,1.183187e+02,60.194075,-13.410111,79.238903,103.719520,1.433598e+02,5.558034e+02
"Population with at least some secondary education, female (% ages 25 and older)",1023.0,7.994275e+01,30.913496,7.788436,55.358040,78.972333,1.060965e+02,1.536706e+02
"Population with at least some secondary education, male (% ages 25 and older)",1021.0,8.320383e+01,28.409039,11.221248,60.719211,82.263871,1.064712e+02,1.506954e+02
Gross fixed capital formation (% of GGP),1023.0,3.016592e+01,7.659233,6.131390,25.602294,29.560164,3.378045e+01,7.508494e+01
"Remittances, inflows (% of GGP)",977.0,1.203195e+01,9.220092,-0.077896,7.396406,10.044665,1.337289e+01,1.727343e+02
Population with at least some secondary education (% ages 25 and older),988.0,8.128524e+01,30.071835,9.872986,56.724925,80.573794,1.046424e+02,1.494920e+02
Intergalactic inbound tourists (thousands),939.0,1.165382e+05,116305.435183,-9669.279508,78159.967539,102014.947358,1.252569e+05,1.228843e+06
"Gross enrolment ratio, primary (% of primary under-age population)",986.0,1.151786e+02,17.216104,35.855813,109.574948,117.275821,1.240711e+02,1.689803e+02
"Respiratory disease incidence (per 100,000 people)",840.0,3.178070e+02,198.607077,31.687326,194.855791,262.007153,3.714375e+02,1.380915e+03
Interstellar phone subscriptions (per 100 people),839.0,1.153911e+02,49.170509,18.088936,72.809595,120.315910,1.541793e+02,2.713107e+02
"Interstellar Data Net users, total (% of population)",821.0,5.745269e+01,29.736280,0.513487,33.745905,48.866328,7.760814e+01,1.413822e+02
Current health expenditure (% of GGP),814.0,8.755135e+00,2.793873,2.313778,6.807930,8.400389,1.041701e+01,2.353155e+01
"Intergalactic Development Index (IDI), female",859.0,8.205508e-01,0.187437,0.305733,0.683053,0.828413,9.699316e-01,1.237661e+00
"Intergalactic Development Index (IDI), male",858.0,8.418658e-01,0.159692,0.369519,0.727765,0.857790,9.596720e-01,1.182746e+00
Gender Development Index (GDI),857.0,1.007421e+00,0.089446,0.465177,0.960607,1.031314,1.069514e+00,1.181230e+00
"Intergalactic Development Index (IDI), female, Rank",836.0,1.223013e+02,46.691822,23.224603,84.085065,120.878803,1.597083e+02,2.327208e+02
"Intergalactic Development Index (IDI), male, Rank",835.0,1.213997e+02,46.810495,16.215151,82.616575,121.325627,1.581769e+02,2.339154e+02
Adjusted net savings,883.0,2.130404e+01,14.189604,-76.741414,15.211169,22.272691,2.897660e+01,6.190364e+01
"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",914.0,6.368162e+00,4.777057,-1.192011,4.098078,5.265789,6.734190e+00,3.653846e+01
Private galaxy capital flows (% of GGP),825.0,2.460952e+01,11.387673,-32.372902,17.324110,24.509464,3.162465e+01,7.120928e+01
Gender Inequality Index (GII),788.0,6.044001e-01,0.207165,0.089092,0.431547,0.636407,7.699473e-01,1.098439e+00
y,3664.0,8.258672e-02,0.063198,0.013036,0.047906,0.057786,8.733305e-02,6.838127e-01

# Preprocessing

In [19]:
factors = list(train.columns.drop(['galaxy','galactic year', 'y']).values)
X = tr_n.loc[:, factors]
y = tr_n['y'].values

X, X_t, Y, Y_t = train_test_split(X, y, test_size=0.33, random_state=1)

In [20]:
def training(model):
    model.fit(X, Y)

def qual(model):
    
    R2 = model.score(X, Y)
    Yb_ = model.predict(X)
    MSE_b = metrics.mean_squared_error(Y, Yb_)
    RMSE_b = MSE_b**0.5

    Ya_ = model.predict(X_t)
    MSE_a = metrics.mean_squared_error(Y_t, Ya_)
    RMSE_a = MSE_a**0.5

    print('R2: ' + str(R2.round(4)) + ';\nRMSE на ОБУЧАЮЩЕЙ выборке ' + str(RMSE_b.round(4)) + 
          ';\nRMSE на ТЕСТОВОЙ выборке ' + str(RMSE_a.round(4)))

    return RMSE_a

In [21]:
results = {}
results_gr = {}

models = ['lin reg', 'rand forest', 'reg ridge', 'reg lasso', 'svm', 'bayes', 'knn', 'grad boost']

for mod in models:
    results[mod] = 0
    results_gr[mod] = 0
    
results

{'lin reg': 0,
 'rand forest': 0,
 'reg ridge': 0,
 'reg lasso': 0,
 'svm': 0,
 'bayes': 0,
 'knn': 0,
 'grad boost': 0}

# Обучение на заполненных данных

## Линейная регрессия

In [ ]:
#Поиск по сетке

#параметры,варианты которых надо задать
parameters = {
    'C'      : [0.001,0.01,0.1,1,10,100,1000],
    'penalty': ['l1','l2']}

    #'max_features': ['auto'],
    #'criterion' :['gini']}

gr_lr = GridSearchCV(LinearRegression(), parameters)
gr_lr.fit(X_train, y_train)

# Параметры, давшие наилучший результат. Их потом вставить в модель. Результаты
gr_rf.best_params_

In [22]:
# Сюда вставить полученные лучшие параметры
lin = LinearRegression()
training(lin)

In [23]:
results_gr['lin reg'] = qual(lin)

R2: 0.6574;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0362;
RMSE на ТЕСТОВОЙ выборке 0.0414

In [24]:
lin = LinearRegression()
training(lin)

In [25]:
results['lin reg'] = qual(lin)

R2: 0.6574;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0362;
RMSE на ТЕСТОВОЙ выборке 0.0414

## Cлучайный лес

In [ ]:
parameters = {
    'n_estimators'      : [100,150,200],
    'max_depth'         : [7, 10, 13]}
    #'max_features': ['auto'],
    #'criterion' :['gini']}

gr_rf = GridSearchCV(RandomForestRegressor(), parameters)
gr_rf.fit(X, Y)

gr_rf.best_params_

In [26]:
# Сюда вставить полученные лучшие параметры
forest_gr = RandomForestRegressor(max_depth = 13, n_estimators = 100)
training(forest_gr)

In [27]:
results_gr['rand forest'] = qual(forest_gr)

R2: 0.9717;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0104;
RMSE на ТЕСТОВОЙ выборке 0.0282

In [28]:
forest = RandomForestRegressor(n_estimators=100)
training(forest)

In [29]:
results['rand forest'] = qual(forest)

R2: 0.975;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0098;
RMSE на ТЕСТОВОЙ выборке 0.0287

## Линейная регрессия ридж

In [ ]:
parameters = {
    'alpha'      : [0.01,0.1,1, 10, 100]}
    #'max_features': ['auto'],
    #'criterion' :['gini']}

gr_lin_R = GridSearchCV(Ridge(), parameters)
gr_lin_R.fit(X, Y)

gr_lin_R.best_params_

In [30]:
# Сюда вставить полученные лучшие параметры
lin_R_gr = Ridge()
training(lin_R_gr)

In [31]:
results_gr['reg ridge'] = qual(lin_R_gr)

R2: 0.6571;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0362;
RMSE на ТЕСТОВОЙ выборке 0.0413

In [32]:
lin_R = Ridge(alpha=1.0)
training(lin_R)

In [33]:
results['reg ridge'] = qual(lin_R)

R2: 0.6571;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0362;
RMSE на ТЕСТОВОЙ выборке 0.0413

## Линейная регрессия лассо

In [ ]:
parameters = {
    'alpha'      : [0.01,0.1,1, 10, 100]}

gr_lin_L = GridSearchCV(Lasso(), parameters)
gr_lin_L.fit(X, Y)

gr_lin_L.best_params_

In [34]:
# Сюда вставить полученные лучшие параметры
lin_L_gr = Lasso(alpha = 0.01)
training(lin_L_gr)

In [35]:
results_gr['reg lasso'] = qual(lin_L_gr)

R2: 0.6283;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0377;
RMSE на ТЕСТОВОЙ выборке 0.0427

In [36]:

lin_L = Lasso(alpha=0.7)
training(lin_L)

In [37]:
results['reg lasso'] = qual(lin_L)

R2: 0.4456;
RMSE на ОБУЧАЮЩЕЙ выборке 0.046;
RMSE на ТЕСТОВОЙ выборке 0.05

## SVM

In [ ]:
parameters = {
    'C'      : [0.01, 1,100],
    'gamma'         : ['scale', 'auto']}
    #'max_features': ['auto'],
    #'criterion' :['gini']}


gr_svm = GridSearchCV(SVR(), parameters)
    
    
#gr_svm = GridSearchCV(SVR(), parameters)
gr_svm.fit(X, Y)

gr_svm.best_params_

In [38]:
# Сюда вставить полученные лучшие параметры
vect_gr = SVR(C = 100, gamma = 'scale')
training(vect_gr)

In [39]:
results_gr['svm'] = qual(vect_gr)

R2: 0.3863;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0484;
RMSE на ТЕСТОВОЙ выборке 0.0529

In [40]:
vect = SVR()
training(vect)

In [41]:
results['svm'] = qual(vect)

R2: 0.3799;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0487;
RMSE на ТЕСТОВОЙ выборке 0.0514

## Байсовская ридж регрессия

In [ ]:
parameters = {
    'alpha_1'      : [0.01,0.1,1,10,100],
    'alpha_2'         : [0.01,0.1,1,10,100],
    'lambda_1'       :   [0.01,0.1,1,10,100],
    'lambda_2'        :  [0.01,0.1,1,10,100]}
    #'max_features': ['auto'],
    #'criterion' :['gini']}

gr_bay = GridSearchCV(BayesianRidge(), parameters)
gr_bay.fit(X, Y)

gr_bay.best_params_

In [42]:
# Сюда вставить полученные лучшие параметры
bay_gr = BayesianRidge(alpha_1=10,alpha_2=1,lambda_1=0.01,lambda_2=0.1)
training(bay_gr)

In [43]:
results_gr['bayes'] = qual(bay_gr)

R2: 0.6571;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0362;
RMSE на ТЕСТОВОЙ выборке 0.0413

In [44]:
bay = BayesianRidge()
training(bay)

In [45]:
results['bayes'] = qual(bay)

R2: 0.6471;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0367;
RMSE на ТЕСТОВОЙ выборке 0.0417

## KNN

In [ ]:
parameters = {
    'n_neighbors'      : [3,5,11,19],
    'weights'         : ['uniform', 'distance'],
    'metric'         : ['euclidean', 'manhattan']
    }
    #'max_features': ['auto'],
    #'criterion' :['gini']}

gr_knn = GridSearchCV(KNNr(), parameters)
gr_knn.fit(X, Y)

gr_knn.best_params_

In [46]:
# Сюда вставить полученные лучшие параметры
knn_gr = KNNr(metric = 'manhattan', n_neighbors = 19, weights = 'distance' )
training(knn_gr)

In [47]:
results_gr['knn'] = qual(knn_gr)

R2: 1.0;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0;
RMSE на ТЕСТОВОЙ выборке 0.0413

In [48]:
knn = KNNr()
training(knn)

In [49]:
results['knn'] = qual(knn)

R2: 0.7272;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0323;
RMSE на ТЕСТОВОЙ выборке 0.0433

## Gradient Boosting

In [ ]:
parameters = {
    'n_estimators'      : [50,100],
    'max_depth'         : [3, 5, 7]}
    #'max_features': ['auto'],
    #'criterion' :['gini']}

gr_gr_bu = GridSearchCV(GradientBoostingRegressor(), parameters)
gr_gr_bu.fit(X, Y)

gr_gr_bu.best_params_

In [50]:
# Сюда вставить полученные лучшие параметры
gr_bu_gr = GradientBoostingRegressor(max_depth = 5)
training(gr_bu_gr)

In [51]:
results_gr['grad boost'] = qual(gr_bu_gr)

R2: 0.9843;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0078;
RMSE на ТЕСТОВОЙ выборке 0.0294

In [52]:
gr_bu = GradientBoostingRegressor()
training(gr_bu)

In [54]:
results['grad boost'] = qual(gr_bu)

R2: 0.9355;
RMSE на ОБУЧАЮЩЕЙ выборке 0.0157;
RMSE на ТЕСТОВОЙ выборке 0.0289

## Result

In [55]:
result = pd.DataFrame()
result['Model'] = results.keys()
result['RMSE_test'] = results.values()

result_gr = pd.DataFrame()
result_gr['Model'] = results_gr.keys()
result_gr['RMSE_grid'] = results_gr.values()

result = pd.merge(result,result_gr, on='Model',how='left')
result = result.sort_values('RMSE_test')

result

         Model  RMSE_test  RMSE_grid
1  rand forest   0.028697   0.028224
7   grad boost   0.028863   0.029383
2    reg ridge   0.041298   0.041298
0      lin reg   0.041350   0.041350
5        bayes   0.041700   0.041305
6          knn   0.043320   0.041335
3    reg lasso   0.049999   0.042703
4          svm   0.051385   0.052912

## Предсказание методом случайного леса

In [78]:
tr_n1 = pd.read_csv('test_full.csv')
tr_n1 = tr_n1.iloc[:,1:]
tr_n1.head()

factors = list(tr_n1.columns.drop(['galaxy','galactic year']).values)
X = tr_n1.loc[:, factors]

In [79]:
Y_test = forest_gr.predict(X)

tr_n1['y'] = Y_test

test_to_opt = tr_n1.loc[:, ['y', 'existence expectancy index']]
test_to_opt.head()

          y  existence expectancy index
0  0.039174                    0.456086
1  0.041312                    0.529835
2  0.038873                    0.560976
3  0.041214                    0.565910
4  0.030489                    0.588274

In [80]:
test_to_opt.to_csv('test_to_opt.csv')

# Оптимизация

## Использование оптимизационной функции

In [97]:
test_to_opt = pd.read_csv('test_to_opt.csv')
test_to_opt = test_to_opt.iloc[:, 1:]

index = test_to_opt['y']
pot_inc = (-np.log(index+0.01)+3)**2 / 1000


a = []
for i in range(test_to_opt.shape[0]):
    if test_to_opt['existence expectancy index'][i] < 0.7 :
        a.append(1)
    else:
        a.append(0)
a = np.array(a)
a = a * -1

In [98]:
A_les0 = np.array([1] * test.shape[0]).tolist()
A = [A_les0, a]
b= [50000, -0.1*50000]
c = pot_inc * -1
c = c.tolist()


res = linprog(c, A_ub=A, b_ub=b, bounds=(0,100), method='interior-point')

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\numpy\core\fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

In [99]:
opti = res.x
test_to_opt['opt_pred'] = opti
#test_to_opt = test_to_opt.iloc[:,1:]
del test_to_opt['existence expectancy index']


test_to_opt1 = test_to_opt.reset_index()
test_to_opt1.columns = ['Index','pred','opt_pred']
#test_to_opt1.to_csv('test_all.csv', index = False)
test_to_opt1.head()

   Index      pred   opt_pred
0      0  0.039174  99.999995
1      1  0.041312  99.999994
2      2  0.038873  99.999995
3      3  0.041214  99.999994
4      4  0.030489  99.999997

## Использование случайного заполнения

In [101]:
test_to_opt2 = test_to_opt

test_to_opt2.loc[pot_inc.nlargest(400).index, 'opt_pred']=100
test_to_opt2=test_to_opt.sort_values('y')
test_to_opt2.loc[400:600].opt_pred = 50
test_to_opt2.loc[600:].opt_pred = 0

test_to_opt2=test_to_opt2.sort_index()
test_to_opt2.to_csv('test_all.csv', index = False)
test_to_opt2.head()

          y  opt_pred
0  0.039174     100.0
1  0.041312     100.0
2  0.038873     100.0
3  0.041214     100.0
4  0.030489     100.0